// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFHiZIi43ScOLMVK2iUCEr5bXoXDbJwr4',
    appId: '1:170355328357:web:18675425b9de746f1ccd8c',
    messagingSenderId: '170355328357',
    projectId: 'shopsmartar-73863',
    authDomain: 'shopsmartar-73863.firebaseapp.com',
    storageBucket: 'shopsmartar-73863.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArobm14kJfWCMTGlKjJq_nlbqSjjO6H3s',
    appId: '1:170355328357:android:98866492bc74ded51ccd8c',
    messagingSenderId: '170355328357',
    projectId: 'shopsmartar-73863',
    storageBucket: 'shopsmartar-73863.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA26YT9LznTslHkvv8IJtCKP4e__IQnZ40',
    appId: '1:170355328357:ios:3456c28dc4cd015b1ccd8c',
    messagingSenderId: '170355328357',
    projectId: 'shopsmartar-73863',
    storageBucket: 'shopsmartar-73863.appspot.com',
    iosBundleId: 'com.example.eCommerceAppWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA26YT9LznTslHkvv8IJtCKP4e__IQnZ40',
    appId: '1:170355328357:ios:cdf82a367760dfe11ccd8c',
    messagingSenderId: '170355328357',
    projectId: 'shopsmartar-73863',
    storageBucket: 'shopsmartar-73863.appspot.com',
    iosBundleId: 'com.example.eCommerceAppWithFirebase.RunnerTests',
  );
}
